# Generated by Django 5.1.4 on 2025-01-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupons',
            new_name='coupon',
        ),
    ]
