# Generated by Django 5.1.4 on 2025-01-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
