# Generated by Django 5.1.4 on 2025-01-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_full_name_address_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
